//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EmployeeFeedbackWebApp.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class FeedbackAssignment
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public FeedbackAssignment()
        {
            this.EndOfYearFeedbacks = new HashSet<EndOfYearFeedback>();
            this.MidYearFeedbacks = new HashSet<MidYearFeedback>();
        }
    
        public long FeedbackAssignmentId { get; set; }
        public long UserId { get; set; }
        public Nullable<long> FeedbackCycleId { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<EndOfYearFeedback> EndOfYearFeedbacks { get; set; }
        public virtual FeedbackCycle FeedbackCycle { get; set; }
        public virtual User User { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<MidYearFeedback> MidYearFeedbacks { get; set; }
    }
}
