//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EmployeeFeedbackWebApp.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class FeedbackCycle
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public FeedbackCycle()
        {
            this.FeedbackAssignments = new HashSet<FeedbackAssignment>();
        }
    
        public long FeedBackCycleId { get; set; }
        public string FeedbackCycleName { get; set; }
        public Nullable<long> MidYearFeedbackCycleId { get; set; }
        public Nullable<long> EOYFeedbackCycleId { get; set; }
        public string IsActive { get; set; }
        public string ReviewPeriodType { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<FeedbackAssignment> FeedbackAssignments { get; set; }
    }
}
